name: Docker

on:
  push:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        images: [ "gcr.io/distroless/static-debian12" ]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      packages: write
      contents: read
      attestations: write
    env:
      REGISTRY: ghcr.io

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: ${{ env.REGISTRY }}/soemii/distroless-healthcheck
          tags: |
            type=semver,pattern=${{matrix.images}}-{{version}}
            type=semver,pattern=${{matrix.images}}-{{major}}.{{minor}}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.PACKAGE_TOKEN }}
      - name: Build and push image
        id: push
        uses: docker/build-push-action@v5.0.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: DISTROLESS_IMAGE=${{ matrix.images }}
