name: Docker

on:
  create:

jobs:
  build:
    strategy:
      matrix:
        images: [ "static-debian12", "java-base-debian12", "java17-debian12", "java21-debian12" ]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      packages: write
      contents: read
      attestations: write
    env:
      REGISTRY: ghcr.io

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/soemii/distroless-healthcheck
          tags: |
            type=semver,prefix=${{matrix.images}}-,pattern={{version}}
            type=semver,prefix=${{matrix.images}}-,pattern={{major}}.{{minor}}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.PACKAGE_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push image
        id: push
        uses: docker/build-push-action@v5.0.0
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: DISTROLESS_IMAGE=${{ matrix.images }}
